import Breadcrumb from "@/components/Breadcrumb";
import Card from "@/parts/Contact/Card";
import Footer from "@/parts/Footer";
import Header from "@/parts/Header";
import SiteMap from "@/parts/SiteMap";
import Head from "next/head";

export default function contact() {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Breadcrumb title={"About us"} />
        <Card />
        <SiteMap />
      </main>
    </>
  );
}
