import Footer from "@/parts/Footer";
import Header from "@/parts/Header";
import Description from "@/parts/HomePage/Description";
import Features from "@/parts/HomePage/Features";
import Helping from "@/parts/HomePage/Helping";
import Hero from "@/parts/HomePage/Hero";
import Quotes from "@/parts/HomePage/Quotes";
import TheySay from "@/parts/HomePage/TheySay";
import SiteMap from "@/parts/SiteMap";
import Head from "next/head";
import { Fragment } from "react";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Contructors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header variant="transparent" />
        <Hero />
         <Helping />
        <Quotes />
        <Description />
        <Features />
        <TheySay />
        <Footer />
        <SiteMap /> 
      </main>
    </Fragment>
  );
}
