import Breadcrumb from "@/components/Breadcrumb";
import Footer from "@/parts/Footer";
import Header from "@/parts/Header";
import OurService from "@/parts/Services/OurService";
import SiteMap from "@/parts/SiteMap";
import Head from "next/head";
import { Fragment } from "react";

export default function services() {
  return (
    <Fragment>
      <Head>
        <title>Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Breadcrumb title={"Services"} />
        <OurService />
        <Footer />
        <SiteMap />
      </main>
    </Fragment>
  );
}
