import Breadcrumb from "@/components/Breadcrumb";
import Footer from "@/parts/Footer";
import Header from "@/parts/Header";
import SiteMap from "@/parts/SiteMap";
import OurWork from "@/parts/Work/OurWork";
import Head from "next/head";
import React from "react";

export default function work() {
  return (
    <>
      <Head>
        <title>Work</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Breadcrumb title={"Work"} />
        <OurWork />
        <Footer />
        <SiteMap/>
      </main>
    </>
  );
}
